### PR TITLE
Added C++ compatibility

### PR DESCRIPTION
**Pull request by tweakdeveloper**

### CODE REVIEW

**Comment by ooxi** [comment]
Looks good! I would love compiling it in C and C++ mode during Travis, any idea on how to do that? I'll have a detailed look at it tomorrow :)

**Comment by tweakdeveloper** [comment]
I'm not sure.  I think that if you added a C++ test program it would compile in C++.

**Comment by tweakdeveloper** [comment]
Does this work for you?

**Comment by ooxi** [comment]
Thanks!

**Pull request merged**
